Crud wines
WildCodeSchool/2022_09_PHP_Lyon_Vin_sur_Vin pull request #12
Opened 2022-10-28 09:07 UTC by CoquilledeLune

front completed for the navbar mobile and screen and for the wines form

2022-10-28 19:20 UTC, aldaitzwild requested changes

2022-10-28 19:20 UTC, aldaitzwild commented on public/assets/css/style.css
> +@media screen and (max-width: 992px)  {
The media queries are forbidden

2022-10-28 19:20 UTC, aldaitzwild commented on public/assets/css/style.css
> +@media screen and (max-width: 702px)  {
Same here.

2022-10-31 10:08 UTC, CoquilledeLune commented
I solved this issue

2022-11-01 13:49 UTC, aldaitzwild approved these changes

2022-11-01 13:49 UTC, merged