Account
WildCodeSchool/2022_09_PHP_Lyon_Vin_sur_Vin pull request #32
Opened 2022-11-17 19:58 UTC by busy-gnl

2022-11-17 22:08 UTC, busy-gnl commented
i swear it's clean i've tried every pages

2022-11-18 10:42 UTC, aldaitzwild requested changes

2022-11-18 10:42 UTC, aldaitzwild commented on public/assets/css/style.css
> +    background-color: #9a7d6c;
This CSS rule is not closed ... and that's the 2nd file on 40 ! Very good proofreading guys...

2022-11-18 15:31 UTC, aldaitzwild requested changes

2022-11-18 15:31 UTC, aldaitzwild commented on src/Controller/AccountService.php
> +    }
Because of the logout function, it's not only a Service class, it's a real Controller ! So you should rename this class "AccountController"

2022-11-18 21:34 UTC, closed without merging